name: ogp_data_extract
description: A new Flutter package project for extracting ogp data on web pages.
version: 0.1.1
homepage: https://github.com/KINTO-JP

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  http: ^0.13.4
  string_validator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
