name: ogp_data_extract
description: Use original library from pub.dev :)
version: 0.1.4
homepage: https://github.com/0xManjeet/ogp_data_extract

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.4
  dio:
  string_validator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
